
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /mutate-azure-jpang-dev-v1alpha1-managedcluster
  failurePolicy: Fail
  name: mmanagedcluster.kb.io
  rules:
  - apiGroups:
    - azure.jpang.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - managedclusters

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: webhook-service
      namespace: system
      path: /validate-azure-jpang-dev-v1alpha1-managedcluster
  failurePolicy: Fail
  name: vmanagedcluster.kb.io
  rules:
  - apiGroups:
    - azure.jpang.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - managedclusters
